version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TAILWIND_DISABLE_LIGHTNINGCSS=true
    volumes:
      - web_node_modules:/app/node_modules
      - web_next_build:/app/apps/web/.next

  app:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - TAILWIND_DISABLE_LIGHTNINGCSS=true
    volumes:
      - app_node_modules:/app/node_modules
      - app_next_build:/app/apps/app/.next

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - TAILWIND_DISABLE_LIGHTNINGCSS=true
    volumes:
      - admin_node_modules:/app/node_modules
      - admin_next_build:/app/apps/admin/.next

volumes:
  web_node_modules:
  web_next_build:
  app_node_modules:
  app_next_build:
  admin_node_modules:
  admin_next_build:
